### 1. Problem Statement

Create a numpy array starting from 2 till 50 with a stepsize of 3

In [1]:
import numpy as np
arr = np.arange(2,51,3)
print(arr)

[ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44 47 50]


### 2. Problem Statement

In [9]:
list1 = []
list2 = []

for x in range(5):
    num = int(input())
    list1.append(num)
arr1 = np.array(list1)
print("Array 1: ", arr1)

for y in range(5):
    num = int(input())
    list2.append(num)
arr2 = np.array(list2)  
print("Array 2: ", arr2)

arr3 = np.concatenate((arr1, arr2))
print("\nConcatenated Array is : ",arr3)

arr4 = np.sort(arr3)
print("Sorted Array is : ",arr4)

3
7
5
4
2
Array 1:  [3 7 5 4 2]
9
2
16
4
1
Array 2:  [ 9  2 16  4  1]

Concatenated Array is :  [ 3  7  5  4  2  9  2 16  4  1]
Sorted Array is :  [ 1  2  2  3  4  4  5  7  9 16]


### 3. Problem Statement

In [12]:
arr1 = np.arange(5)
print("Array :",arr1)
print("Dimesnion : ",arr1.ndim)
print("Array Size : ",arr1.size)

Array : [0 1 2 3 4]
Dimesnion :  1
Array Size :  5


### 4. Problem Statement

In [4]:
arr_1d = ([1,2,3,4])
arr_2d = np.reshape(arr_1d, (2,2))
print(arr_2d)

[[1 2]
 [3 4]]


### 5. Problem Statement

In [16]:
arr1 = np.array([[10,20],[30,40]])
print("Array 1 : ",arr1)
arr2 = np.array([[80,0],[60,20]])
print("Array 2 : ",arr2)

ver_arr = np.vstack((arr1,arr2))
print("\nVertical Array:\n ",ver_arr)

hor_arr = np.hstack((arr1,arr2))
print("\nHorizontal Array:\n ",hor_arr)


Array 1 :  [[10 20]
 [30 40]]
Array 2 :  [[80  0]
 [60 20]]

Vertical Array:
  [[10 20]
 [30 40]
 [80  0]
 [60 20]]

Horizontal Array:
  [[10 20 80  0]
 [30 40 60 20]]


### 6. Problem Statement

In [17]:
arr = np.array([2,4,2,1,5,1,6,7])

(unique, counts) = np.unique(arr, return_counts=True)
frequencies = np.asarray((unique, counts)).T

print(frequencies)

[[1 2]
 [2 2]
 [4 1]
 [5 1]
 [6 1]
 [7 1]]
